#! /bin/bash

cd "$APPDIR"

# default qt5 location
if [ -d /usr/lib/x86_64-linux-gnu/qt5 ]; then
    exec ./yuzu-bwrap.sh
else
    # qt5 on Steam Deck (as qt)
    if [ -d /usr/lib/qt ]; then
        exec ./yuzu-bwrap.sh
    else
        # default qt6 location
        if [ -d /usr/lib/x86_64-linux-gnu/qt6 ]; then
            exec ./yuzu-bwrap.sh
        else
            # qt6 on Steam Deck
            if [ -d /usr/lib/qt6 ]; then
                exec ./yuzu-bwrap.sh
            else
                exec ./yuzu.sh
            fi
        fi
    fi
fi
