vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO azahar-emu/mcl
    REF 7b08d83418f628b800dfac1c9a16c3f59036fbad
    SHA512 9c6ba624cb22ef622f78046a82abb99bf5026284ba17dfacaf46ac842cbd3b0f515f5ba45a1598c7671318a78a2e648db72ce8d10e7537f34e39800bdcb57694
)

# Install headers (repo uses include/mcl path)
if (EXISTS "${SOURCE_PATH}/include")
    file(INSTALL "${SOURCE_PATH}/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
else()
    # Fallback: install src/include or, as a last resort, only header files from the repository
    if (EXISTS "${SOURCE_PATH}/src/include")
        file(INSTALL "${SOURCE_PATH}/src/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include")
    else()
        # Avoid installing the entire repository; only install header files into include/mcl
        # Use COPY with FILES_MATCHING to preserve subdirectory structure and exclude non-public dirs
        file(COPY "${SOURCE_PATH}/"
            DESTINATION "${CURRENT_PACKAGES_DIR}/include/mcl"
            FILES_MATCHING
            PATTERN "*.h"
            PATTERN "*.hpp"
            PATTERN "*.hxx"
            PATTERN "*.hh"
            PATTERN "tests/" EXCLUDE
            PATTERN "examples/" EXCLUDE
            PATTERN "third_party/" EXCLUDE
            PATTERN "vendor/" EXCLUDE
        )
    endif()
endif()

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/mcl" RENAME copyright)

# Provide a relocatable CMake config for consumers using find_package(mcl CONFIG ...)
file(WRITE "${CURRENT_PACKAGES_DIR}/share/mcl/mclConfig.cmake"
"# mcl CMake configuration generated by portfile\n"
"get_filename_component(_MCL_PREFIX \"\${CMAKE_CURRENT_LIST_DIR}/../..\" ABSOLUTE)\n\n"
"if(NOT TARGET mcl::mcl)\n"
"    add_library(mcl::mcl INTERFACE IMPORTED)\n"
"    set_target_properties(mcl::mcl PROPERTIES\n"
"        INTERFACE_INCLUDE_DIRECTORIES \"\${_MCL_PREFIX}/include\"\n"
"    )\n"
"endif()\n\n"
"# Some consumers reference merry::mcl; provide a compatibility alias\n"
"if(NOT TARGET merry::mcl AND TARGET mcl::mcl)\n"
"    add_library(merry::mcl ALIAS mcl::mcl)\n"
"endif()\n"
)

# Provide a version file so find_package(mcl 0.1.12 EXACT ...) works
file(WRITE "${CURRENT_PACKAGES_DIR}/share/mcl/mclConfigVersion.cmake"
"set(PACKAGE_VERSION \"0.1.12\")\n\n"
"if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)\n"
"    set(PACKAGE_VERSION_COMPATIBLE FALSE)\n"
"else()\n"
"    set(PACKAGE_VERSION_COMPATIBLE TRUE)\n"
"    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)\n"
"        set(PACKAGE_VERSION_EXACT TRUE)\n"
"    endif()\n"
"endif()\n"
)
