#! /bin/bash

cd "$APPDIR"

if [ -d /usr/lib/aarch64-linux-gnu/qt5 ]; then
    exec ./yuzu-bwrap.sh
else
    if [ -d /usr/lib/aarch64-linux-gnu/qt6 ]; then
        exec ./yuzu-bwrap.sh
    else
        exec ./yuzu.sh
    fi
fi
