#!/bin/bash

# SPDX-FileCopyrightText: 2024 suyu Emulator Project
# SPDX-License-Identifier: GPL-3.0-or-later

# Eden-Suyu Merge Preparation Script
# This script prepares the repository for merging improvements from Eden

set -e

echo "🚀 Suyu Eden Merge Preparation Script"
echo "======================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    print_error "Not in a git repository!"
    exit 1
fi

# Check if we're in the correct repository (suyu)
if ! grep -q "suyu" README.md 2>/dev/null; then
    print_warning "This doesn't appear to be the suyu repository"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_status "Preparing repository for Eden merge..."

# 1. Ensure we're on the main branch and up to date
print_status "Checking current branch and status..."
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ] && [ "$CURRENT_BRANCH" != "master" ]; then
    print_warning "Not on main/master branch (currently on: $CURRENT_BRANCH)"
    read -p "Switch to main branch? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git checkout main 2>/dev/null || git checkout master 2>/dev/null || {
            print_error "Could not switch to main/master branch"
            exit 1
        }
    fi
fi

# 2. Check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
    print_warning "You have uncommitted changes"
    git status --porcelain
    read -p "Stash changes and continue? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git stash push -m "Pre-Eden-merge stash $(date)"
        print_success "Changes stashed"
    else
        print_error "Please commit or stash your changes before continuing"
        exit 1
    fi
fi

# 3. Create EDEN-MERGE branch if it doesn't exist
print_status "Creating EDEN-MERGE branch..."
if git show-ref --verify --quiet refs/heads/EDEN-MERGE; then
    print_warning "EDEN-MERGE branch already exists"
    read -p "Delete and recreate? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git branch -D EDEN-MERGE
        print_success "Deleted existing EDEN-MERGE branch"
    else
        print_status "Using existing EDEN-MERGE branch"
        git checkout EDEN-MERGE
    fi
else
    git checkout -b EDEN-MERGE
    print_success "Created EDEN-MERGE branch"
fi

# 4. Create baseline metrics file
print_status "Creating baseline metrics..."
cat > BASELINE_METRICS.md << 'EOF'
# Suyu Baseline Metrics (Pre-Eden Merge)

This file contains baseline metrics captured before merging Eden improvements.
Use this to measure the impact of Eden integration.

## Build Information
- **Date**: $(date)
- **Commit**: $(git rev-parse HEAD)
- **Branch**: $(git branch --show-current)

## Build System Status
- **CMake Version**: $(cmake --version | head -n1)
- **VCPKG Status**: $(if [ -d "vcpkg_installed" ]; then echo "Installed"; else echo "Not installed"; fi)
- **Dependencies**: See vcpkg.json for current dependency versions

## Performance Baselines
TODO: Add performance benchmarks after Eden merge
- Game loading times
- Frame rates for test games
- Memory usage patterns
- Shader compilation times

## Compatibility Baselines
TODO: Add compatibility metrics after Eden merge
- Number of playable games
- Known issues count
- Crash frequency metrics

## Code Quality Metrics
- **Lines of Code**: $(find src -name "*.cpp" -o -name "*.h" | xargs wc -l | tail -n1)
- **Test Coverage**: TODO - implement coverage reporting
- **Static Analysis**: TODO - add static analysis metrics

---
Generated by prepare-eden-merge.sh on $(date)
EOF

print_success "Created baseline metrics file"

# 5. Create branding protection script
print_status "Creating branding protection tools..."
cat > scripts/validate-branding.sh << 'EOF'
#!/bin/bash

# Suyu Branding Validation Script
# Ensures Suyu branding is preserved during Eden merge

set -e

echo "🔍 Validating Suyu Branding..."

ERRORS=0

# Check for Eden branding that shouldn't be there
check_file_content() {
    local file="$1"
    local pattern="$2"
    local description="$3"
    
    if [ -f "$file" ] && grep -qi "$pattern" "$file"; then
        echo "❌ Found $description in $file"
        grep -n -i "$pattern" "$file"
        ERRORS=$((ERRORS + 1))
    fi
}

# Check for prohibited Eden references
check_file_content "README.md" "eden emulator" "Eden branding"
check_file_content "src/suyu_qt/aboutdialog.cpp" "eden" "Eden references in about dialog"
check_file_content "src/suyu_qt/main.cpp" "eden" "Eden references in main application"

# Check that Suyu branding is preserved
check_suyu_branding() {
    local file="$1"
    local description="$2"
    
    if [ -f "$file" ] && ! grep -qi "suyu" "$file"; then
        echo "❌ Missing Suyu branding in $description ($file)"
        ERRORS=$((ERRORS + 1))
    fi
}

check_suyu_branding "README.md" "README file"
check_suyu_branding "CMakeLists.txt" "CMake project"

# Check for proper application name
if [ -f "src/suyu_qt/main.cpp" ]; then
    if ! grep -q "setApplicationName.*suyu" src/suyu_qt/main.cpp; then
        echo "❌ Application name not set to 'suyu' in main.cpp"
        ERRORS=$((ERRORS + 1))
    fi
fi

if [ $ERRORS -eq 0 ]; then
    echo "✅ All branding validation checks passed!"
    exit 0
else
    echo "❌ Found $ERRORS branding issues that need to be fixed"
    exit 1
fi
EOF

chmod +x scripts/validate-branding.sh
print_success "Created branding validation script"

# 6. Create Eden integration checklist
print_status "Creating integration checklist..."
cat > EDEN_INTEGRATION_CHECKLIST.md << 'EOF'
# Eden Integration Checklist

Use this checklist for each Eden improvement being integrated.

## Pre-Integration
- [ ] Eden improvement identified and documented
- [ ] Impact assessment completed
- [ ] Branding implications reviewed
- [ ] Test plan created

## Integration Process
- [ ] Feature branch created from EDEN-MERGE
- [ ] Eden changes applied with Suyu branding preserved
- [ ] Code review completed
- [ ] Branding validation passed (`./scripts/validate-branding.sh`)
- [ ] Build verification completed on all platforms
- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Performance impact assessed

## Post-Integration
- [ ] Documentation updated
- [ ] Changelog entry added
- [ ] Community testing completed
- [ ] Regression testing passed
- [ ] Merged to EDEN-MERGE branch

## Final Validation
- [ ] Full test suite passes
- [ ] Performance benchmarks meet expectations
- [ ] No branding issues detected
- [ ] User experience validated
- [ ] Ready for main branch merge

---
**Integration Date**: ___________  
**Integrated By**: ___________  
**Eden Improvement**: ___________  
**Impact Level**: [ ] Critical [ ] High [ ] Medium [ ] Low  
EOF

print_success "Created integration checklist"

# 7. Update .gitignore if needed
print_status "Updating .gitignore..."
if ! grep -q "BASELINE_METRICS.md" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# Eden merge artifacts" >> .gitignore
    echo "eden-repo/" >> .gitignore
    echo "eden-analysis/" >> .gitignore
    echo "*.eden-backup" >> .gitignore
    print_success "Updated .gitignore"
fi

# 8. Create initial commit on EDEN-MERGE branch
print_status "Creating initial commit on EDEN-MERGE branch..."
git add .
git commit -m "feat: prepare repository for Eden merge integration

- Add comprehensive Eden merge plan documentation
- Create branding validation tools
- Set up integration checklist and baseline metrics
- Prepare EDEN-MERGE branch for systematic integration

This commit establishes the foundation for merging improvements
from Eden while preserving Suyu branding and custom features."

print_success "Initial commit created on EDEN-MERGE branch"

# 9. Display next steps
echo ""
echo "🎉 Repository prepared for Eden merge!"
echo "======================================"
echo ""
echo "Next steps:"
echo "1. Review EDEN_MERGE_PLAN.md for detailed integration strategy"
echo "2. Set up access to Eden repository for analysis"
echo "3. Run baseline performance tests and update BASELINE_METRICS.md"
echo "4. Begin systematic integration following the plan"
echo ""
echo "Useful commands:"
echo "  ./scripts/validate-branding.sh  - Validate Suyu branding"
echo "  ./scripts/fix-vcpkg-build.ps1   - Fix any build issues"
echo "  git checkout main               - Return to main branch"
echo "  git checkout EDEN-MERGE         - Switch to integration branch"
echo ""
echo "Current branch: $(git branch --show-current)"
echo "Ready to begin Eden integration! 🚀"
EOF

chmod +x scripts/prepare-eden-merge.sh

<brief_summary>
Now let me create a comprehensive build system improvement script that addresses any remaining build issues and optimizes the build process.
</brief_summary>

<function_calls>
<invoke name="str_replace_editor">
<parameter name="path">/workspace/scripts/improve-build-system.sh