# SPDX-FileCopyrightText: 2021 yuzu Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: suyu-ci

on:
  push:
    branches: [ master, dev ]
    tags: [ "*" ]
  pull_request:
    branches: [ master, dev, metal-dev, fix/dynarmic-vcpkg-msvc-ci ]

jobs:
  reuse:
    name: Check REUSE Specification
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'suyu-emu/SuyuEclipse' }}
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v1
